config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/', to: 'weather#weather_info'
  post '/', to: 'weather#weather_info', as: 'weather_info'
  get '/*all', to: 'weather#weather_info'
end

app/models/address.rb
class Address
  attr_reader :street, :city, :state, :zip_code
  include ActiveModel::Validations
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, format: { with: /\A\d{5}/, :message => 'consists of 6 digits' }

  def initialize(address_params)
    @street = address_params[:street]
    @city = address_params[:city]
    @state = address_params[:state]
    @zip_code = address_params[:zip_code]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  before_action :validate_address
  def weather_info
    weather_client = WeatherClient.new(@address)
    @weather_forecast, @cache_hit = weather_client.get_weather_info
  end

  protected

  def render_weather_info
    render template: 'weather/weather_info'
  end

  def validate_address
    render_weather_info and return if request.get?
    @address = Address.new(address_params)
    render_weather_info and return unless @address.valid?
  end
  def address_params
    params.require(:address).permit(:street, :city, :state, :zip_code)
    params[:address]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TekSystemAsgn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/_hourly_info.html.erb
<div>
  <% unless ind.zero?%>
    <h5><%= "after #{ind} hours" %><h5>
  <% end %>
  <ul>
    <% if ind.zero?%>
      <li>current temperature: <%= data[:temp]%></li>
      <li>feels like: <%= data[:feels_like]%></li>
    <% end %>
    <li>Minimum temperature: <%= data[:temp_min] %></li>
    <li>Maximum Temperature: <%= data[:temp_max] %></li>
  </ul>
</div>

app/views/weather/weather_info.html.erb
<html>
<head>
  <title>Weather info</title>
</head>
<body>
  <h1>Enter Address details</h1>
  <div><%= @address.errors.full_messages.join(',') if @address&.invalid? %> </div>
  <%= form_tag weather_info_path, class: "search-form", data: { turbo:false } do |f| %>
    <label for="street">Street:</label>
    <input type="text" name="address[street]" value="<%= @address&.street %>" id="street">

    <label for="city">City:</label>
    <input type="text" name="address[city]" value="<%= @address&.city %>" id="city">

    <label for="state">State:</label>
    <input type="text" name="address[state]" value="<%= @address&.state %>" id="state">

    <label for="zip_code">Zip Code:</label>
    <input type="text" name="address[zip_code]" value="<%= @address&.zip_code %>" id="zip_code">

    <input type="submit" value="Submit">
  <% end %>

  <% if @cache_hit %>
    <h4>rendering results from cache</h4>
  <% end %>
  <% @weather_forecast&.each_with_index do |data, ind| %>
    <%= render partial: "weather/hourly_info", locals: {data: data, ind: ind}  %>
  <% end %>
</body>
</html>